[build]
  functions = "functions"

[[redirects]]
  from = "/"
  to = "https://itsmehran.github.io/ytdownload/downloader.html"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/mp3-converter"
  to = "https://itsmehran.github.io/ytdownload/mp3-converter.html"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/downloader"
  to = "https://itsmehran.github.io/ytdownload/downloader.html"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
